# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/jiffies.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/jiffies.proto\x12\x18smaragdine.protos.sample\"\xc3\x01\n\nCpuReading\x12\x0b\n\x03\x63pu\x18\x01 \x02(\r\x12\x0e\n\x06socket\x18\x0c \x02(\r\x12\x0c\n\x04user\x18\x02 \x01(\r\x12\x0c\n\x04nice\x18\x03 \x01(\r\x12\x0e\n\x06system\x18\x04 \x01(\r\x12\x0c\n\x04idle\x18\x05 \x01(\r\x12\x0e\n\x06iowait\x18\x06 \x01(\r\x12\x0b\n\x03irq\x18\x07 \x01(\r\x12\x0f\n\x07softirq\x18\x08 \x01(\r\x12\r\n\x05steal\x18\t \x01(\r\x12\r\n\x05guest\x18\n \x01(\r\x12\x12\n\nguest_nice\x18\x0b \x01(\r\"U\n\tCpuSample\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x35\n\x07reading\x18\x02 \x03(\x0b\x32$.smaragdine.protos.sample.CpuReading\"W\n\x0bTaskReading\x12\x0f\n\x07task_id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x63pu\x18\x03 \x02(\r\x12\x0c\n\x04user\x18\x04 \x01(\r\x12\x0e\n\x06system\x18\x05 \x01(\r\"Z\n\rProcessSample\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x36\n\x07reading\x18\x02 \x03(\x0b\x32%.smaragdine.protos.sample.TaskReadingB\x1c\n\x18smaragdine.protos.sampleP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.jiffies_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030smaragdine.protos.sampleP\001'
  _globals['_CPUREADING']._serialized_start=51
  _globals['_CPUREADING']._serialized_end=246
  _globals['_CPUSAMPLE']._serialized_start=248
  _globals['_CPUSAMPLE']._serialized_end=333
  _globals['_TASKREADING']._serialized_start=335
  _globals['_TASKREADING']._serialized_end=422
  _globals['_PROCESSSAMPLE']._serialized_start=424
  _globals['_PROCESSSAMPLE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
