# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/nvml.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/nvml.proto\x12\x18smaragdine.protos.sample\"A\n\x0bNvmlReading\x12\r\n\x05index\x18\x03 \x02(\r\x12\x0e\n\x06\x62us_id\x18\x01 \x02(\t\x12\x13\n\x0bpower_usage\x18\x02 \x01(\r\"W\n\nNvmlSample\x12\x11\n\ttimestamp\x18\x01 \x02(\x04\x12\x36\n\x07reading\x18\x02 \x03(\x0b\x32%.smaragdine.protos.sample.NvmlReadingB\x1c\n\x18smaragdine.protos.sampleP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.nvml_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030smaragdine.protos.sampleP\001'
  _globals['_NVMLREADING']._serialized_start=47
  _globals['_NVMLREADING']._serialized_end=112
  _globals['_NVMLSAMPLE']._serialized_start=114
  _globals['_NVMLSAMPLE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
