# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/sampler.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from smaragdine.protos import sample_pb2 as protos_dot_sample__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/sampler.proto\x12\x18smaragdine.protos.sample\x1a\x13protos/sample.proto\"+\n\x0cStartRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x04\x12\x0e\n\x06period\x18\x02 \x01(\x04\"\x0f\n\rStartResponse\"\x1a\n\x0bStopRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x04\"\x0e\n\x0cStopResponse\"\x1a\n\x0bReadRequest\x12\x0b\n\x03pid\x18\x01 \x01(\x04\"?\n\x0cReadResponse\x12/\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32!.smaragdine.protos.sample.DataSet2\x97\x02\n\x07Sampler\x12Z\n\x05Start\x12&.smaragdine.protos.sample.StartRequest\x1a\'.smaragdine.protos.sample.StartResponse\"\x00\x12W\n\x04Stop\x12%.smaragdine.protos.sample.StopRequest\x1a&.smaragdine.protos.sample.StopResponse\"\x00\x12W\n\x04Read\x12%.smaragdine.protos.sample.ReadRequest\x1a&.smaragdine.protos.sample.ReadResponse\"\x00\x42\x1d\n\x19smaragdine.protos.samplerP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.sampler_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031smaragdine.protos.samplerP\001'
  _globals['_STARTREQUEST']._serialized_start=71
  _globals['_STARTREQUEST']._serialized_end=114
  _globals['_STARTRESPONSE']._serialized_start=116
  _globals['_STARTRESPONSE']._serialized_end=131
  _globals['_STOPREQUEST']._serialized_start=133
  _globals['_STOPREQUEST']._serialized_end=159
  _globals['_STOPRESPONSE']._serialized_start=161
  _globals['_STOPRESPONSE']._serialized_end=175
  _globals['_READREQUEST']._serialized_start=177
  _globals['_READREQUEST']._serialized_end=203
  _globals['_READRESPONSE']._serialized_start=205
  _globals['_READRESPONSE']._serialized_end=268
  _globals['_SAMPLER']._serialized_start=271
  _globals['_SAMPLER']._serialized_end=550
# @@protoc_insertion_point(module_scope)
