# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/sample.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from smaragdine.protos import jiffies_pb2 as protos_dot_jiffies__pb2
from smaragdine.protos import nvml_pb2 as protos_dot_nvml__pb2
from smaragdine.protos import rapl_pb2 as protos_dot_rapl__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/sample.proto\x12\x18smaragdine.protos.sample\x1a\x14protos/jiffies.proto\x1a\x11protos/nvml.proto\x1a\x11protos/rapl.proto\"\xec\x01\n\x06Sample\x12\x34\n\x04rapl\x18\x01 \x01(\x0b\x32$.smaragdine.protos.sample.RaplSampleH\x00\x12\x34\n\x04nvml\x18\x05 \x01(\x0b\x32$.smaragdine.protos.sample.NvmlSampleH\x00\x12\x32\n\x03\x63pu\x18\x02 \x01(\x0b\x32#.smaragdine.protos.sample.CpuSampleH\x00\x12:\n\x07process\x18\x03 \x01(\x0b\x32\'.smaragdine.protos.sample.ProcessSampleH\x00\x42\x06\n\x04\x64\x61ta\"\xdd\x01\n\x07\x44\x61taSet\x12\x32\n\x04rapl\x18\x01 \x03(\x0b\x32$.smaragdine.protos.sample.RaplSample\x12\x32\n\x04nvml\x18\x05 \x03(\x0b\x32$.smaragdine.protos.sample.NvmlSample\x12\x30\n\x03\x63pu\x18\x02 \x03(\x0b\x32#.smaragdine.protos.sample.CpuSample\x12\x38\n\x07process\x18\x03 \x03(\x0b\x32\'.smaragdine.protos.sample.ProcessSampleB\x1c\n\x18smaragdine.protos.sampleP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.sample_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030smaragdine.protos.sampleP\001'
  _globals['_SAMPLE']._serialized_start=110
  _globals['_SAMPLE']._serialized_end=346
  _globals['_DATASET']._serialized_start=349
  _globals['_DATASET']._serialized_end=570
# @@protoc_insertion_point(module_scope)
