# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from smaragdine.protos import sampler_pb2 as protos_dot_sampler__pb2


class SamplerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/smaragdine.protos.sample.Sampler/Start',
                request_serializer=protos_dot_sampler__pb2.StartRequest.SerializeToString,
                response_deserializer=protos_dot_sampler__pb2.StartResponse.FromString,
                )
        self.Stop = channel.unary_unary(
                '/smaragdine.protos.sample.Sampler/Stop',
                request_serializer=protos_dot_sampler__pb2.StopRequest.SerializeToString,
                response_deserializer=protos_dot_sampler__pb2.StopResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/smaragdine.protos.sample.Sampler/Read',
                request_serializer=protos_dot_sampler__pb2.ReadRequest.SerializeToString,
                response_deserializer=protos_dot_sampler__pb2.ReadResponse.FromString,
                )


class SamplerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SamplerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=protos_dot_sampler__pb2.StartRequest.FromString,
                    response_serializer=protos_dot_sampler__pb2.StartResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=protos_dot_sampler__pb2.StopRequest.FromString,
                    response_serializer=protos_dot_sampler__pb2.StopResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=protos_dot_sampler__pb2.ReadRequest.FromString,
                    response_serializer=protos_dot_sampler__pb2.ReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smaragdine.protos.sample.Sampler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Sampler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smaragdine.protos.sample.Sampler/Start',
            protos_dot_sampler__pb2.StartRequest.SerializeToString,
            protos_dot_sampler__pb2.StartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smaragdine.protos.sample.Sampler/Stop',
            protos_dot_sampler__pb2.StopRequest.SerializeToString,
            protos_dot_sampler__pb2.StopResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smaragdine.protos.sample.Sampler/Read',
            protos_dot_sampler__pb2.ReadRequest.SerializeToString,
            protos_dot_sampler__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
